import Link from 'next/link'

export default function Footer() {
  return (
    <footer
      style={{
        borderTop: '1px solid var(--color-border)',
        backgroundColor: 'var(--color-base)',
        marginTop: '6rem',
      }}
    >
      <div
        className="container"
        style={{
          paddingBlock: '3rem',
          display: 'flex',
          flexDirection: 'column',
          gap: '1.5rem',
        }}
      >
        {/* Top row */}
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: '1.5rem',
            justifyContent: 'space-between',
            alignItems: 'flex-start',
          }}
        >
          {/* Brand */}
          <div>
            <p
              style={{
                fontFamily: 'var(--font-display)',
                fontSize: '1.1rem',
                fontWeight: 600,
                color: 'var(--color-ink)',
                marginBottom: '0.25rem',
              }}
            >
              Egon Notebooks
            </p>
            <p style={{ fontSize: '0.8rem', color: 'var(--color-ink-muted)', maxWidth: '320px' }}>
              Structured knowledge about your inner life. Yours to keep.
            </p>
          </div>

          {/* Links */}
          <nav
            aria-label="Footer navigation"
            style={{ display: 'flex', gap: '1.5rem', flexWrap: 'wrap', alignItems: 'center' }}
          >
            <Link
              href="https://github.com/egon-notebooks"
              target="_blank"
              rel="noopener noreferrer"
              style={{ fontSize: '0.8rem', color: 'var(--color-ink-muted)' }}
            >
              GitHub
            </Link>
            <Link href="/registry" style={{ fontSize: '0.8rem', color: 'var(--color-ink-muted)' }}>
              Registry
            </Link>
            <Link href="/about" style={{ fontSize: '0.8rem', color: 'var(--color-ink-muted)' }}>
              About
            </Link>
          </nav>
        </div>

        {/* Disclaimer */}
        <p
          style={{
            fontSize: '0.73rem',
            color: 'var(--color-ink-muted)',
            lineHeight: 1.6,
            maxWidth: '720px',
            borderTop: '1px solid var(--color-border)',
            paddingTop: '1.25rem',
          }}
        >
          Content generated by Claude (Anthropic) and reviewed by a mental health professional.
          For educational purposes only — not a substitute for professional mental health advice,
          diagnosis, or treatment. If you are in crisis, please contact a mental health professional
          or a crisis service in your country.
          Licensed under{' '}
          <a
            href="https://creativecommons.org/licenses/by-nc/4.0/"
            target="_blank"
            rel="noopener noreferrer"
          >
            CC BY-NC 4.0
          </a>
          .
        </p>

        <p style={{ fontSize: '0.73rem', color: 'var(--color-ink-muted)' }}>
          © {new Date().getFullYear()} Egon Notebooks
        </p>
      </div>
    </footer>
  )
}
